In [ ]:
# Q1

In [47]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.5'

In [ ]:
# Q2

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [5]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [10]:
df.describe

<bound method NDFrame.describe of       model_year  origin fuel_type         drivetrain  num_doors  \
0           2006  Europe  Gasoline  Front-wheel drive          4   
1           2008  Europe    Diesel  Front-wheel drive          4   
2           1996    Asia  Gasoline  Front-wheel drive          5   
3           1989  Europe  Gasoline  Front-wheel drive          4   
4           1994     USA    Diesel  Front-wheel drive          3   
...          ...     ...       ...                ...        ...   
9995        2005     USA  Gasoline    All-wheel drive          4   
9996        1993    Asia  Gasoline    All-wheel drive          2   
9997        2014     USA  Gasoline    All-wheel drive          3   
9998        2004     USA    Hybrid   Rear-wheel drive          5   
9999        2011     USA    Diesel  Front-wheel drive          4   

      engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                    2180              6       243.0            3870   
1    

In [ ]:
# Q3

In [11]:
df.fuel_type.nunique()

3

In [12]:
df.nunique()

model_year              50
origin                   3
fuel_type                3
drivetrain               3
num_doors                4
engine_displacement    127
num_cylinders            5
horsepower             153
vehicle_weight         176
acceleration            93
fuel_efficiency_mpg    188
dtype: int64

In [ ]:
# Q4

In [14]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [ ]:
# Q5

In [15]:
df['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [ ]:
# Q6

In [17]:
df['horsepower'].median()

np.float64(254.0)

In [19]:
df['horsepower'].describe()

count    9123.000000
mean      254.446016
std        22.844613
min       171.000000
25%       239.000000
50%       254.000000
75%       270.000000
max       334.000000
Name: horsepower, dtype: float64

In [21]:
mode = df['horsepower'].mode()

In [22]:
df['horsepower'] = df['horsepower'].fillna(mode)

In [24]:
df['horsepower'].median()

np.float64(254.0)

In [25]:
df['horsepower'].describe()

count    9123.000000
mean      254.446016
std        22.844613
min       171.000000
25%       239.000000
50%       254.000000
75%       270.000000
max       334.000000
Name: horsepower, dtype: float64

In [26]:
# Q7

In [27]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0


In [41]:
df.loc[df['origin'] == 'Asia',['vehicle_weight', 'model_year']] .head(7)

,vehicle_weight,model_year
2,4240,1996
6,4310,1992
8,4230,1997
10,4420,1978
15,3950,2007
16,4750,2021
22,4450,2019


In [39]:
X = df.loc[df['origin'] == 'Asia',['vehicle_weight', 'model_year']] .head(7).to_numpy()

In [40]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [44]:
XTX = X.T.dot(X)

In [53]:
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [51]:
XTX_inv = np.linalg.inv(XTX)

In [54]:
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [50]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [56]:
w = (XTX_inv.dot(X.T)).dot(y)

In [57]:
w

array([0.13644777, 0.2327492 ])

In [58]:
w.sum()

np.float64(0.36919696904925486)